CREATE DATABASE IF NOT EXISTS zodiac_app
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE zodiac_app;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    zodiac VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    consent TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    zodiac VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    message_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
